quorum:
    url: ${RPC_URL:http://localhost:22000}
    moderator: ${PRIVATE_KEY}
    admin: ${PRIVATE_KEY}
    chainId: ${NETWORK_CHAIN_ID} 
    contractAddress: 
        booking: ${CONTRACT_ADDRESS}
        sportFacility: ${CONTRACT_ADDRESS}
        management: ${CONTRACT_ADDRESS}