quorum:
    url: ${RPC_URL:http://localhost:22000}
    moderator: ${PRIVATE_KEY}
    admin: ${PRIVATE_KEY}
    chainId: ${NETWORK_CHAIN_ID} 
    contractAddress: 
        booking: ${CONTRACT_ADDRESS}
        sportFacility: ${CONTRACT_ADDRESS}
        management: ${CONTRACT_ADDRESS}

jwt:
    secret: ${JWT_SCERET}
    accessExpiry: 
    refreshExpiry: 

cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS} # blockchain and frontend 

pinata:
    jwt: ${PINATA_JWT:}
    gateway: ${PINATA_GATEWAY:}

app:
    backend-url: ${BACKEND_URL:http://localhost:8080}

automation:
    admin-email: ${ADMIN_EMAIL:} # one of the admin email
    admin-address: ${ADMIN_ADDRESS:} # one of the admin blockchain address