quorum:
    url: ${RPC_URL:http://localhost:22000}
    moderator: ${PRIVATE_KEY_MODERATOR}
    admin: ${PRIVATE_KEY_ADMIN}
    chainId: ${NETWORK_CHAIN_ID} 
    contractAddress: 
        booking: ${CONTRACT_ADDRESS_BOOKING}
        sportFacility: ${CONTRACT_ADDRESS_SPORTFACILITY}
        management: ${CONTRACT_ADDRESS_MANAGEMENT}

jwt:
    secret: ${JWT_SCERET}
    accessExpiry: ${JWT_ACCESS_EXP}
    refreshExpiry: ${JWT_REFRESH_EXP}

cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS} # blockchain and frontend 

pinata:
    jwt: ${PINATA_JWT:}
    gateway: ${PINATA_GATEWAY:}

app:
    backend-url: ${BACKEND_URL:http://localhost:8080}

automation:
    admin-email: ${ADMIN_EMAIL:} # one of the admin email
    admin-address: ${ADMIN_ADDRESS:} # one of the admin blockchain address